export {default as Navigation} from "./NavigationFolder/navigation"
export {default as Sidebar} from "./Sidebar/sidebar"
export {default as Footer} from "./Footer/footer"
export {default as Button} from "./Button/btn";
export {default as Banner} from "./BannerFolder/banner";
export {default as MainHeader} from "./Header/mainheader";
export {default as Card} from "./CardsFolder/card";
export {default as ApproachCard} from "./CardsFolder/ApproachCard";
export {default as JoinUs} from "./JoinUs";
export {default as WorkCard} from "./CardsFolder/workCard";